// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

function createDeck(param) {
  return /* :: */[
          "asdf",
          /* [] */0
        ];
}

function shuffleDeck(param) {
  return /* :: */[
          "asdf",
          /* [] */0
        ];
}

var Deck_000 = /* cardSuits : :: */[
  "\xe2\x9d\xa4\xef\xb8\x8f",
  /* :: */[
    "\xe2\x99\xa0\xef\xb8\x8f",
    /* :: */[
      "\xe2\x99\xa3\xef\xb8\x8f",
      /* :: */[
        "\xe2\x99\xa6\xef\xb8\x8f",
        /* [] */0
      ]
    ]
  ]
];

var Deck_001 = /* cardRanks : :: */[
  "A",
  /* :: */[
    "2",
    /* :: */[
      "3",
      /* :: */[
        "4",
        /* :: */[
          "5",
          /* :: */[
            "6",
            /* :: */[
              "7",
              /* :: */[
                "8",
                /* :: */[
                  "9",
                  /* :: */[
                    "10",
                    /* :: */[
                      "J",
                      /* :: */[
                        "Q",
                        /* :: */[
                          "K",
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var Deck = /* module */[
  Deck_000,
  Deck_001,
  /* createDeck */createDeck,
  /* shuffleDeck */shuffleDeck
];

exports.Deck = Deck;
/*  Not a pure module */
